### ISSUE TITLE
xvhdl getting disabled after update of SublimeLinter

### ISSUE THREAD

**Issue by apurvanandan1997** [BrunoJJE/SublimeLinter-contrib-xvhdl#3]
SublimeLinter: ERROR:
=====================

xvhdl: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.

SublimeLinter: ERROR:
=====================

xvhdl disabled. 'cls.defaults' is mandatory and MUST be a dict.

**Comment by BrunoJJE** [comment]
Merged.
