### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jeanthom** [BrunoJJE/SublimeLinter-contrib-xvhdl#9]
Hi,

The current release (1.0.0) of SublimeLinter-contrib-xvhdl is unusable due to #4. This has been updated in master, but has yet to arrive to Package Control. Could you please release 1.0.1?

Thanks,
Jean.

**Comment by BrunoJJE** [comment]
Done.
https://github.com/BrunoJJE/SublimeLinter-contrib-xvhdl/releases/tag/1.0.1

**Comment by jeanthom** [comment]
Thanks!
